// src/lib/compiler/proseCompiler.ts
import { createHash } from "node:crypto";

export const COMPILER_VERSION = "prose-compiler@0.1.0";

function sha256Hex(s: string) {
  return createHash("sha256").update(s).digest("hex");
}

function stableStringify(v: any): string {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(stableStringify).join(",")}]`;
  const keys = Object.keys(v).sort();
  return `{${keys.map((k) => JSON.stringify(k) + ":" + stableStringify(v[k])).join(",")}}`;
}

export type CompileInput =
  | {
      kind: "task";
      task: {
        id: string;
        title: string;
        description: string;
        deliverablesSpec: any[];
        contextSpec: any[];
        mountsSpec: any[];
      };
    }
  | {
      kind: "workflow_version";
      workflowVersion: {
        id: string;
        workflowId: string;
        version: number;
        definition: any; // already immutable snapshot
      };
    };

export type CompileResult = {
  compilerVersion: string;
  sourceHash: string;
  programText: string;
  programHash: string;
};

export function compileToProse(input: CompileInput): CompileResult {
  // 1) deterministic source snapshot
  const source = (() => {
    if (input.kind === "task") {
      const t = input.task;
      return {
        kind: "task",
        id: t.id,
        title: t.title,
        description: t.description ?? "",
        deliverablesSpec: t.deliverablesSpec ?? [],
        contextSpec: t.contextSpec ?? [],
        mountsSpec: t.mountsSpec ?? [],
      };
    }
    const w = input.workflowVersion;
    return {
      kind: "workflow_version",
      id: w.id,
      workflowId: w.workflowId,
      version: w.version,
      definition: w.definition ?? {},
    };
  })();

  const sourceJson = stableStringify(source);
  const sourceHash = sha256Hex(sourceJson);

  // 2) deterministic program emitter (starter program)
  // Keep this aligned with your UI event model.
  const programText =
`# generated by ${COMPILER_VERSION}
# source_hash: ${sourceHash}

agent captain:
  model: sonnet
  prompt: "You coordinate the run and produce a final result binding."

# v0 starter program (deterministic)
session "Collect context + constraints"
session "Execute task plan"
output result = session "Write deliverables + finalize"
`;

  const programHash = sha256Hex(programText);

  return {
    compilerVersion: COMPILER_VERSION,
    sourceHash,
    programText,
    programHash,
  };
}